---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: Copying setup folder
      become: false
      copy:
        src: ./setup
        dest: ./
        owner: ubuntu
        group: ubuntu
        mode: 0777
        
    - name: Copying yml
      become: false
      copy:
        src: ./docker-compose.yml
        dest: ./
        owner: ubuntu
        group: ubuntu
        mode: 0777
        
    - name: Copying script file
      become: false
      copy:
        src: ./scriptfile.sh
        dest: ./
        owner: ubuntu
        group: ubuntu
        mode: 0777
    - name: Changing permission
      shell: sudo chmod 777 /var/run/docker.sock
        
    - name: Run Docker compose
      shell: ./scriptfile.sh
