---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: Copying setup folder
      become: true 
      copy:
        src: ./setup
        dest: ./
        owner: ssv
        group: ssv
        mode: 0777
    - name: Copying script file
      become: true 
      copy:
        src: ./scriptfile.sh
        dest: ./
        owner: ssv
        group: ssv  
        mode: 077
    - name : Run Docker compose
      ansible.builtin.shell:
    	cmd: ./scriptfile.sh

